apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  storageClassName: sc-local
  capacity:
    storage: 20Gi
  #volumeMode: Block
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/test-volume
  #persistentVolumeReclaimPolicy: Delete
  #local:
  #  path: /tmp/test-volume
  #nodeAffinity:
  #  required:
  #    nodeSelectorTerms:
  #    - matchExpressions:
  #      - key: kubernetes.io/hostname
  #        operator: In
  #        values:
  #        - master-node
