apiVersion: v1
kind: Pod
metadata:
  name: "fio-{{ .Values.rtc }}-emptydir-memory"
  namespace: io-test
spec:
  {{- if ne .Values.rtc "runc" }}
  runtimeClassName: "kata-{{ .Values.rtc }}"
  {{- end }}
  containers:
  - name: fio
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    env:
    - name: RTC
      value: "{{ .Values.rtc }}"
    - name: VOLUME
      value: emptydir-memory
    resources:
      requests:
        cpu: "{{ .Values.resources.requests.cpu }}"
        memory: "{{ .Values.resources.requests.memory }}"
      limits:
        cpu: "{{ .Values.resources.limits.cpu }}"
        memory: "{{ .Values.resources.limits.memory }}"
    volumeMounts:
    - mountPath: /test-volume
      name: emptydir-volume
    - mountPath: /results
      name: result-volume
  volumes:
  - name: emptydir-volume
    emptyDir:
      medium: Memory
      sizeLimit: "8Gi"
  - name: result-volume
    hostPath:
      path: /root/results
      type: DirectoryOrCreate
