apiVersion: v1
kind: Pod
metadata:
  name: "fio-{{ .Values.rtc }}-hostpath"
  namespace: io-test
spec:
  {{- if ne .Values.rtc "runc" }}
  runtimeClassName: "kata-{{ .Values.rtc }}"
  {{- end }}
  containers:
  - name: fio
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    env:
    - name: RTC
      value: "{{ .Values.rtc }}"
    - name: VOLUME
      value: hostpath
    resources:
      requests:
        cpu: "{{ .Values.resources.requests.cpu }}"
        memory: "{{ .Values.resources.requests.memory }}"
      limits:
        cpu: "{{ .Values.resources.limits.cpu }}"
        memory: "{{ .Values.resources.limits.memory }}"
    volumeMounts:
    - mountPath: /test-volume
      name: hostpath-volume
    - mountPath: /results
      name: result-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp/test-volume
      type: DirectoryOrCreate
  - name: result-volume
    hostPath:
      path: /root/results
      type: DirectoryOrCreate
