apiVersion: v1
kind: Pod
metadata:
  name: "fio-{{ .Values.rtc }}-emptydir-disk"
  namespace: io-test
spec:
  runtimeClassName: "kata-{{ .Values.rtc }}"
  containers:
  - name: fio
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    resources:
      requests:
        cpu: "{{ .Values.resources.requests.cpu }}"
        memory: "{{ .Values.resources.requests.memory }}"
      limits:
        cpu: "{{ .Values.resources.limits.cpu }}"
        memory: "{{ .Values.resources.limits.memory }}"
    volumeMounts:
    - mountPath: /test-volume
      name: emptydir-volume
    - mountPath: /results
      name: result-volume
  volumes:
  - name: emptydir-volume
    emptyDir: {}
  - name: result-volume
    hostPath:
      path: /home/results
      type: DirectoryOrCreate
